#' @title Important principal components
#' @description Return PCA filtered for just the important principal components
#'
#' @param pca principal component object generated by \link[stats]{prcomp}.
#' @param num.pcs maximum number of principal components to retain. If 
#'   \code{NULL}, only components that explain more variance than 1 / number of 
#'   variables will be retained.
#'
#' @return list containing \code{rotation}, \code{x}, and \code{importance} 
#'   elements with only important components or \code{n.pcs}, 
#'   whichever is smaller.
#'
#' @author Eric Archer \email{eric.archer@@noaa.gov}
#'
impPCs <- function(pca, num.pcs = NULL) {
  # number of important PCs = as many as account for expected variance
  imp.gt.exp <- pca$importance["Proportion of Variance", ] >= (1 / ncol(pca$importance))
  n.imp <- max(1, which.min(imp.gt.exp) - 1)
  num.pcs <- if(is.null(num.pcs)) n.imp else min(num.pcs, n.imp)
  
  # extract important PCs from object
  pca$rotation <- pca$rotation[, 1:num.pcs]
  pca$x<- pca$x[, 1:num.pcs]
  pca$importance <- pca$importance[, 1:num.pcs]
  
  # remove unnecessary elements
  pca$sdev <- pca$center <- pca$scale <- NULL
  
  pca
}
